name: Test
on:
  push:
    branches:
      - master
      - preview
      - ci
      - release/v2.0
  pull_request:
    branches:
      - master
      - preview
jobs:
  publish:
    name: Publish
    if: contains(github.ref,'ci') && github.head_ref == null
    runs-on: ubuntu-latest
    steps:
      - shell: pwsh
        run: |
          "I Ran!: ${{github.head_ref}} "
